apiVersion: v1
kind: Service
metadata:
  name: eks-workshop
  namespace: eks-workshop
  labels:
    app: eks-workshop
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-workshop
